package com.rafa.conciliacion.business.model;

import lombok.Data;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;


/**
 * Model of the Banking Operation microservice. A Banking Operation is a banking movement that has been done in
 * a period of time, with some amount, by a customer, on an account.
 * To be counted and to avoid mistakes, the movement has to be reconciliated.
 * This model has an id autogenerated.
 *
 * @author rperez-beato@viewnext.com
 */
@Data
@Entity
public class BankingOperation implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private Date date;
    private String customerId;
    private String account;
    private double amount;
    private boolean isReconciliated;

}
